### ISSUE TITLE
Código ejemplo de app Syrus Mobile

### ISSUE THREAD

**Issue by marcorivm** [dctdevelop/pegasus#1]
Hola, en la conferencia mencionaron que podrían compartir el código de esta app: https://play.google.com/store/apps/details?id=com.syrus.app será posible??

**Comment by dctdevelop** [comment]
Hola @marcorivm el código de syrus mobile esta un poco depreciado. Tenemos el código de Syrus Road Side Assistance, la cual esta un poco mas actualizada y utiliza el API. 

https://github.com/dctdevelop/syrus-rsa

Saludos
