### ISSUE TITLE
cambio API

### ISSUE THREAD

**Issue by dcruz1** [dctdevelop/pegasus#2]
Quisiera que por favor cambien el criterio de búsqueda para la siguiente url

https://dct.artimo.com.co/api/counters

actualmente se usa el campo "vid" para especificar el vehículo del que se requieren los contadores. Necesito que se use el campo "device_id" en su lugar

**Comment by dctdevelop** [comment]
@dcruz1 Todos los eventos son indexados por el `vehicle id`, esto facilita la búsqueda y operaciones (/rawdata, /counters, etc).

un vehículo puede tener varios dispositivos, por lo cual una búsqueda por `device_id` resulta siendo no optima dado que puede terminar en varias particiones. 

Para obtener el vid que necesitas de el device, puedes hacer una petición
a `/devices/:imei?select=vehicle`

En caso tal de que el dispositivo cambie de vehículo, vamos a agregar un nuevo campo al recurso de `/devices` identico al campo de `associations`  en el recurso `/vehicles`

```json
"associations": [
{
"vehicle_id": 37,
"device_id": 356612020474922,
"id": 56,
"association": true,
"time": 1320789362.698
},
{
"vehicle_id": 37,
"device_id": 356612020474922,
"id": 87,
"association": false,
"time": 1324496362.663
},
...
]
```

de esta manera puedes sacar las vids necesarias para las consultas en /rawdata y /counters.
